In [6]:
import pandas as pd

In [7]:
pd.__version__

'2.2.2'

In [13]:

url = 'https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv'
df = pd.read_csv(url)
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [16]:
length =  len(df)
length

2160

In [18]:
number_laptops = df['Brand'].nunique()
number_laptops

27

In [22]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [39]:
df[df['Brand'] == 'Dell']['Final Price'].max()

3936.0

In [61]:
screen_median = df['Screen'].median()
screen_mode = df['Screen'].mode()[0]
screen_median,screen_mode

(15.6, 15.6)

In [58]:
most_frequent_screen = df['Screen'].mode()[0]
most_frequent_screen

15.6

In [59]:
df['Screen'] = df['Screen'].fillna(most_frequent_screen)
screen_median = df['Screen'].median()
screen_median

15.6

In [73]:
filtered_df = df[
    df['Brand'] == 'Innjoo'
][['RAM','Storage','Screen']]

In [75]:
import numpy as np
X = np.matrix(filtered_df)
X

matrix([[  8. , 256. ,  15.6],
        [  8. , 512. ,  15.6],
        [  4. ,  64. ,  14.1],
        [  6. ,  64. ,  14.1],
        [  6. , 128. ,  14.1],
        [  6. , 128. ,  14.1]])

In [87]:

transposed_X = X.T
transposed_X


matrix([[  8. ,   8. ,   4. ,   6. ,   6. ,   6. ],
        [256. , 512. ,  64. ,  64. , 128. , 128. ],
        [ 15.6,  15.6,  14.1,  14.1,  14.1,  14.1]])

In [115]:
XTX = transposed_X.dot(X)
XTX

matrix([[2.52000e+02, 8.32000e+03, 5.59800e+02],
        [8.32000e+03, 3.68640e+05, 1.73952e+04],
        [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [116]:
import numpy as np
determinant = np.linalg.det(XTX)
print("Determinant:", determinant)

Determinant: 611414507.519992


In [117]:
import numpy as np

XTX_inv = np.linalg.inv(XTX)
XTX_inv

matrix([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
        [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
        [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [118]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [120]:

XTXinv_transposed_X = XTX_inv.dot(transposed_X)
XTXinv_transposed_X
w = np.dot(XTXinv_transposed_X,y)
w

matrix([[45.58076606,  0.42783519, 45.29127938]])